<?php

/**
 * @file
 * Contains isp.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function isp_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the isp module.
    case 'help.page.isp':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The internet.') . '</p>';
      return $output;

    default:
  }
}
/**
 * Implements hook_toolbar_alter().
 */
function isp_toolbar_alter(&$items) {
  $items['administration']['#attached']['library'][] = 'isp/toolbar';
}

/**
 * Implements hook_preprocess_HOOK() for menu__role_menu.
 */
function isp_preprocess_menu__role_menu(&$variables) {
  $icons = [
    'isp.system_administrator.system_administration' => 'fa fa-foursquare',
  ];
  _isp_set_menu_items_icon($variables['items'], $icons);
}

function _isp_set_menu_items_icon(&$items, $icons) {
  foreach ($items as $key => $item) {
    if (isset($icons[$key])) {
      $items[$key]['icon'] = $icons[$key];
    }
    if (!empty($item['below'])) {
      _isp_set_menu_items_icon($item['below'], $icons);
    }
  }
}

/**
 * Implements hook_locale_translation_projects_alter().
 */
function isp_locale_translation_projects_alter(&$projects) {
  $path = drupal_get_path('module', 'isp');
  $projects['drupal']['info']['interface translation project'] = 'translation';
  $projects['drupal']['info']['interface translation server pattern'] = $path . '/translations/drupal.%language.po';
}