<?php

/**
 * @file
 * Contains isp.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function isp_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the isp module.
    case 'help.page.isp':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The internet.') . '</p>';
      return $output;

    default:
  }
}

