<?php

/**
 * @file
 * Contains isp_server.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function isp_server_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the isp_server module.
    case 'help.page.isp_server':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The server of isp.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function isp_server_theme() {
  $theme = [];
  $theme['isp_server'] = [
    'render element' => 'elements',
    'file' => 'isp_server.page.inc',
    'template' => 'isp_server',
  ];
  $theme['isp_server_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'isp_server.page.inc',
  ];
  return $theme;
}

/**
* Implements hook_theme_suggestions_HOOK().
*/
function isp_server_theme_suggestions_isp_server(array $variables) {
  $suggestions = [];
  $entity = $variables['elements']['#isp_server'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'isp_server__' . $sanitized_view_mode;
  $suggestions[] = 'isp_server__' . $entity->bundle();
  $suggestions[] = 'isp_server__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'isp_server__' . $entity->id();
  $suggestions[] = 'isp_server__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}
