<?php

/**
 * @file
 * Contains isp_commerce_data_demo.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function isp_commerce_data_demo_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the isp_commerce_data_demo module.
    case 'help.page.isp_commerce_data_demo':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_demo_data_info().
 */
function isp_commerce_data_demo_demo_data_info() {
  $path = drupal_get_path('module', 'isp_commerce_data_demo') . '/tests/data';
  return [
    [
      'id' => 'store_csv',
      'source' => [
        'path' => $path . '/store.csv',
      ],
    ],
  ];
}